version: '3.8'
services:
  dev-db:
    image: postgres:13
    container_name: Hazel-Saloon
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Hazel_BACKEND
    networks:
      - zaigee

networks:
  zaigee:
